export const products = [
  {
    id: 1,
    type: 'face',
    imgUrl:'img/oil.jpg',
    name: 'Hydrophilic oil',
    price: 160,
  },
  {
    id: 2,
    type: 'face',
    imgUrl:'img/oil.jpg',
    name: 'Hydrophilic oil',
    price: 160,
  },
  {
    id: 3,
    type: 'face',
    imgUrl:'img/oil.jpg',
    name: 'Hydrophilic oil',
    price: 160,
  },
  {
    id: 4,
    type: 'face',
    imgUrl:'img/oil.jpg',
    name: 'Hydrophilic oil',
    price: 160,
  },
  {
    id: 5,
    type: 'face',
    imgUrl:'img/oil.jpg',
    name: 'Hydrophilic oil',
    price: 160,
  },
  {
    id: 6,
    type: 'body',
    imgUrl:'img/ubtan.jpg',
    name: 'Ubtan',
    price: 200,
  },
  {
    id: 7,
    type: 'body',
    imgUrl:'img/ubtan.jpg',
    name: 'Ubtan',
    price: 200,
  },
  {
    id: 8,
    type: 'body',
    imgUrl:'img/ubtan.jpg',
    name: 'Ubtan',
    price: 200,
  },
  {
    id: 9,
    type: 'body',
    imgUrl:'img/ubtan.jpg',
    name: 'Ubtan',
    price: 200,
  },
  {
    id: 10,
    type: 'hair',
    imgUrl:'img/shampoo.jpg',
    name: 'Almond Shampoo',
    price: 100,
  },
  {
    id: 11,
    type: 'hair',
    imgUrl:'img/shampoo.jpg',
    name: 'Almond Shampoo',
    price: 100,
  },
  {
    id: 12,
    type: 'hair',
    imgUrl:'img/shampoo.jpg',
    name: 'Almond Shampoo',
    price: 100,
  },
  {
    id: 13,
    type: 'candles',
    imgUrl:'img/candle-p.jpg',
    name: 'Deluxe Scented Candle',
    price: 80,
  },
  {
    id: 14,
    type: 'candles',
    imgUrl:'img/candle-p.jpg',
    name: 'Deluxe Scented Candle',
    price: 80,
  },
  {
    id: 15,
    type: 'candles',
    imgUrl:'img/candle-p.jpg',
    name: 'Deluxe Scented Candle',
    price: 80,
  },
  {
    id: 16,
    type: 'candles',
    imgUrl:'img/candle-p.jpg',
    name: 'Deluxe Scented Candle',
    price: 80,
  },
  {
    id: 15,
    type: 'candles',
    imgUrl:'img/candle-p.jpg',
    name: 'Deluxe Scented Candle',
    price: 80,
  },
];